# Workflow for autoamting feature branch CICD
# Steps in feature branch CICD:
# 


name:  Salesforce feature branch workflow

on:
  push:
    branches:
      - feature/*   # Trigger on any feature branch push

jobs:
  deploy-to-scratch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.SF_AUTH_URL }}
          version: latest

      - name: Authenticate to Dev Hub
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
          SFDX_LOG_LEVEL: DEBUG
        run: |
          # Write private key to a temporary file
          echo "${SF_JWT_KEY}" > /tmp/server.key
          sfdx auth:jwt:grant --clientid $SF_CLIENT_ID \
                             --jwtkeyfile /tmp/server.key \
                             --username $SF_USERNAME \
                             --instanceurl https://login.salesforce.com \
                             --set-default-dev-hub

      - name: Create Scratch Org
        run: |
          # Create scratch org with correct flags
          sfdx org create scratch \
            --definition-file config/project-scratch-def.json \
            --alias CI_Scratch \
            --duration-days 3 \
            --set-default \
            --wait 3 || true
          sfdx org list --all

      - name: Set Scratch Org as default
        run:  sf config set default-org=CI_Scratch

      - name: Deploy Source to Scratch Org
        run: sf project deploy start --target-org CI_Scratch

      - name: Run Apex Tests
        run: sf apex test run --target-org CI_Scratch --result-format human --wait 10

      - name: Delete Scratch Org
        run: sf org delete scratch --target-org CI_Scratch --noprompt


  
