# Workflow for autoamting feature branch CICD
# Steps in feature branch CICD:
# 


name:  Salesforce feature branch workflow

on:
  push:
    branches:
      - feature/*   # Trigger on any feature branch push

jobs:
  deploy-to-scratch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: forcedotcom/salesforcedx-action@v2

      - name: Authenticate to Dev Hub
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
        run: |
          echo "${SF_JWT_KEY}" > assets/server.key
          sfdx auth:jwt:grant --clientid $SF_CLIENT_ID \
                             --jwtkeyfile assets/server.key \
                             --username $SF_USERNAME \
                             --instanceurl https://login.salesforce.com

      - name: Create Scratch Org
        run: |
          sfdx force:org:create -f config/project-scratch-def.json -a CI_Scratch -d 7
          sfdx force:org:display -u CI_Scratch

      - name: Deploy Source to Scratch Org
        run: sfdx force:source:push -u CI_Scratch

      - name: Run Apex Tests
        run: sfdx force:apex:test:run -u CI_Scratch --resultformat human --wait 10

      - name: Delete Scratch Org
        run: sfdx force:org:delete -u CI_Scratch -p


  
